services:
  app:
    build: .
    image: nemogb-app
    container_name: nemogb-container
    ports:
      - "3838:3838"
    volumes:
      - ./R:/srv/shiny-server/
      - ./www:/srv/shiny-server/www/
